= vim-select-more: extension to vim-select

Extend https://github.com/habamax/vim-select[vim-select] with more sources.

See the link:showcase.adoc[animated gifs].


== Installation

If you use package/plugin manager, consult their documentation.

For manual installation clone this repository to your
`~/.vim/pack/plugins/start/` path, where `plugins` subdirectory is arbitrary.

NOTE: for windows users replace `~/.vim` to `~/vimfiles`.


== Mappings

There are no default global mappings -- create your own.

.Safe (will not create mappings if plugin was not loaded)
[source,vim]
------------------------------------------------------------------------------
" add it to ~/.vim/after/plugin/select.vim
if exists("g:loaded_select")
    nmap <leader>h <Plug>(SelectHelp)
    nmap <leader>; <Plug>(SelectCmd)
    nmap <leader>: <Plug>(SelectCmdHistory)
    nmap <leader>/ <Plug>(SelectBufLine)
    nmap <leader>fc <Plug>(SelectColors)
    nmap <leader>fh <Plug>(SelectHighlight)
    nmap <leader>ft <Plug>(SelectBufTag)
    nmap <leader>fg <Plug>(SelectGitFile)
    nmap <leader>fT <Plug>(SelectToDo)
endif
------------------------------------------------------------------------------

or

.Regular
[source,vim]
------------------------------------------------------------------------------
" add it to your vimrc
nmap <leader>h <Plug>(SelectHelp)
nmap <leader>; <Plug>(SelectCmd)
nmap <leader>: <Plug>(SelectCmdHistory)
nmap <leader>/ <Plug>(SelectBufLine)
nmap <leader>fc <Plug>(SelectColors)
nmap <leader>fh <Plug>(SelectHighlight)
nmap <leader>ft <Plug>(SelectBufTag)
nmap <leader>fg <Plug>(SelectGitFile)
nmap <leader>fT <Plug>(SelectToDo)
------------------------------------------------------------------------------


== Commands

* `:Select help` tags from all help files.
+
NOTE: External tool `ripgrep` is required.

* `:Select command` from `:ex` and put it on command line.

* `:Select cmdhistory` and put it on command line.

* `:Select bufline` and go to it.

* `:Select colors` and apply it.

* `:Select highlight` group and:

1. Transform it to proper |:highlight| command.
2. Copy it to unnamed register `"`.
2. Put it to command line.

* `:Select buftag` -- select buffer tag and go to it.
+
NOTE: External tool `ctags` is required.

* `:Select gitfile` -- select file from git repo of the current working directory.

* `:Select todo` -- select TODO:, FIXME: or XXX: and go to it.
+
NOTE: External tool `ripgrep` is required.
